### ISSUE TITLE
updated ban?

### ISSUE THREAD

**Issue by oodvg** [suvanl/delet3-suggestions#10]
Hey! its me again. Sorry I've haven't made any new suggestions for Delet3. However, for the new mute [command](https://github.com/DS-Development/delet/issues/265), are you able to do it with the ban system as well if you haven't already? just thought I'd ask! just thought it would be with most of the Moderation commands. also, can we talk on discord?

**Comment by suvanl** [comment]
Hey! Unfortunately I've been really slow lately when it comes to working on delet3, so I haven't actually written the mute command yet. I will, however, be trying to implement your suggestion into it, and if all goes fine, it'll most likely scale to the ban command (and any other moderation commands, where necessary) with no issues.
I'm happy to message you on Discord, what's your tag?

**Comment by NotSure70** [comment]
DVG#6945

**Comment by oodvg** [comment]
no worries. take your time. yourself comes before other things. i hope you are doing well

**Comment by suvanl** [comment]
thanks a lot - hope you're doing well too!

**Comment by suvanl** [comment]
Hey,

delet3's source code is now public and exists here: https://github.com/suvanl/delet3.
All future issues/pull requests regarding delet should be created on the delet3 repository.

By the way, your suggestion has been implemented for the ban command. I still need to create a mute command, but the logic relating to your suggestion will remain pretty much the same. I did have to make one small change - rather than reacting with A, B, C, or D, the user types their chosen letter. Working with reactions for something like this turned out to be a bit of a nightmare, but I'll consider implementing reactions in the future.

Also, thanks for all your suggestions so far!
