### ISSUE TITLE
maintenance command

### ISSUE THREAD

**Issue by oodvg** [suvanl/delet3-suggestions#3]
this should be a bot owner only command

after you run [prefix]maintenance, the bot should reply maintenance mode "actived? or "going into maintenance mode!"

if someone other than a permlevel of 2 (just incase if something goes wrong then moderators can still take action with the bot),  the bot should reply `${message.author} I am currently in maintenance mode.`

**Comment by suvanl** [comment]
The first way of doing this that comes to mind is to have the maintenance command change a boolean `maintenance` setting to `true`. However, all settings are guild-oriented, and this would be more of a "global" setting, which currently isn't possible to do, and it isn't something I think would be worth implementing. 

A setting would be required because, when the bot is undergoing maintenance, it usually would frequently restart (meaning it could be offline a lot anyway), as things are being tested and changed, so the bot needs a way of "remembering" its maintenance state.
