### ISSUE TITLE
Using mongodb instead of sqlite for storing data.

### ISSUE THREAD

**Issue by 0zul** [suvanl/delet3-suggestions#6]
Using mongodb atlas or local hosted for storing server data, user and other data is really useful as mongodb provides 512 MB which is wayyy more than enough for a lot of bots having 20k+ guilds and provides low latency data read and write.

**Comment by suvanl** [comment]
Yep, delet3 already uses MongoDB for storing all guild/user/other data. Thanks anyway!

**Comment by 0zul** [comment]
@suvanl I never knew. I apologise for creating a useless issue over there.

**Comment by oodvg** [comment]
I think it should be like Delet 2.8.3 in my opinion. make a different branch. between sqlite and mongo. but i dont have the say in this.

**Comment by suvanl** [comment]
@IamTheRealSami that's understandable, no need to apologise for that!

@pika32223 I think sticking to just MongoDB would make more sense. Having two different types of database doesn't seem very beneficial, because one type would never get used (in fact, delet 2.8.3's MongoDB branch was never actually developed, but the original intention was to merge that branch into master and replace sqlite).
