### ISSUE TITLE
djs12

### ISSUE THREAD

**Issue by CodeWithJosh875** [suvanl/delet3-suggestions#9]
Hello. Discord updated to v12 some months ago and im wondering if someone in your team could update this new bot in it? hope to see this updated bot soon with much improvements, less bugs, and much more commands!

**Comment by suvanl** [comment]
Thanks for letting me know! Unfortunately, I haven't really had much time to focus on developing delet3 as of late. I've just updated delet3's discord.js version to 12.4.1 (it's been on v12 since the start anyway, unlike the old version of delet).

The bot's source code will be made public soon, so you can see and potentially contribute to the changes being made.
